language: python
python:
  - "3.6"

env:
  - EMAIL=cloudflare.kz21@torque.mikesoh.com API_KEY=$GLOBAL_API_KEY
  - API_KEY=$API_TOKEN

before_script:
  - bash .travis/create_template.bash

script:
  - python cloudflare-ddns.py -f -c .travis/cf_ddns.conf

before_deploy:
  - pip install --user pyinstaller
  - pyinstaller --onefile ./cloudflare-ddns.spec

deploy:
  provider: releases
  api_key: $GITHUB_API_TOKEN
  file: ./dist/cloudflare-ddns/cloudflare-ddns
  skip_cleanup: true
  draft: true
  on:
    branch: master
