env:
  - BUILD_ID=${TRAVIS_BUILD_NUMBER}-${TRAVIS_COMMIT:0:7}

jobs:
  include:
    - stage: "Test and Build"
      name: "Build using Pyinstaller (Linux-amd64)"
      os: linux
      language: python
      python: "3.6"
      script: 
        - bash .travis/test_python3.bash
        - bash .travis/build_binary.bash
    - name: "Build using Pyinstaller (Linux-arm64)"
      if: branch = master AND type in (pull_request, push)
      arch: arm64
      os: linux
      language: python
      python: "3.6"
      script: 
        - bash .travis/test_python3.bash
        - bash .travis/build_binary.bash
    - name: "Build using Pyinstaller (Mac OS)"
      if: branch = master AND (type in (pull_request, push) OR tag IS present)
      os: osx
      osx_image: xcode11.2
      language: shell
      before_install:
        - python -m pip install --upgrade pip
      install:
        - python -m pip install -r requirements.txt
      script: 
        - bash .travis/test_python3.bash
        - bash .travis/build_binary.bash
    - name: "Build using Pyinstaller (Windows)"
      if: branch = master AND (type in (pull_request, push) OR tag IS present)
      os: windows
      language: shell
      env: 
        - BUILD_ID=${TRAVIS_BUILD_NUMBER}-${TRAVIS_COMMIT:0:7}
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH
      before_install: 
        - echo $BUILD_ID
        - choco install python --version 3.7.6
        - python -m pip install --upgrade pip
      install:
        - python -m pip install -r requirements.txt
      script: 
#       - bash .travis/test_python3.bash
        - bash .travis/build_binary.bash
    - stage: "Test Binaries"
      name: "Linux-amd64"
      os: linux
      language: bash
      script: 
        - bash .travis/test_binary.bash
    - name: "Linux-arm64"
      if: branch = master AND (type in (pull_request, push) OR tag IS present)
      arch: arm64
      os: linux
      language: bash
      script: 
        - bash .travis/test_binary.bash
    - name: "Mac OS X"
      if: branch = master AND (type in (pull_request, push) OR tag IS present)
      os: osx
      language: shell
      script: 
        - bash .travis/test_binary.bash
#    - name: "Windows"
#      if: branch = master AND (type in (pull_request, push) OR tag IS present)
#      os: windows
#      language: shell
#      script: 
#       - bash .travis/test_binary.bash
    - stage: "Create Release Draft"
      os: linux
      language: python
      python: "3.6"
      if: branch = master AND type = push
      install:
        - pip install awscli
      script:
        - mkdir build
        - aws s3 cp s3://${AWS_TRAVIS_DEPLOY_BUCKET}/cloudflare_ddns/${BUILD_ID}/ ./build/ --recursive
        - ls -lR ./build
        - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
        - echo ${TRAVIS_TAG}
        - git tag $TRAVIS_TAG
      deploy:
        provider: releases
        token: $GITHUB_API_TOKEN
        file_glob: true
        file: ./build/*
        cleanup: false
        draft: true
        edge: true
        on:
          branch: master
          tags: true
      after_deploy:
        - aws s3 rm s3://${AWS_TRAVIS_DEPLOY_BUCKET}/cloudflare_ddns/ --recursive
