language: python
python:
  - "3.6"

env:
  - BUILD_ID=${TRAVIS_COMMIT:0:7}-${TRAVIS_BUILD_NUMBER}

jobs:
  include:
    - stage: "Test and Build"
      name: "Build using Pyinstaller (Linux-amd64)"
      os: linux
      script: 
        - bash .travis/test_python3.bash
        - bash .travis/build_binary.bash
        - bash .travis/test_binary.bash
    - name: "Build using Pyinstaller (Linux-arm64)"
      arch:
        - arm64
      os: linux
      script: 
        - bash .travis/test_python3.bash
        - bash .travis/build_binary.bash
        - bash .travis/test_binary.bash
    - name: "Build using Pyinstaller (Mac OS)"
      os: osx
      osx_image: xcode11.2
      language: shell
      before_install:
        - python -m pip install --upgrade pip
      install:
        - python -m pip install -r requirements.txt
      script: 
        - bash .travis/test_python3.bash
        - bash .travis/build_binary.bash
        - bash .travis/test_binary.bash
    - name: "Build using Pyinstaller (Windows)"
      os: windows
      language: shell
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      before_install: 
        - choco install python --version 3.8.1
        - python -m pip install --upgrade pip
      install:
        - python -m pip install -r requirements.txt
      script: 
        - bash .travis/test_python3.bash
        - bash .travis/build_binary.bash
        - bash .travis/test_binary.bash
    - stage: "Create Release Draft"
      os: linux
      if: branch = master
      deploy:
        provider: releases
        token: $GITHUB_API_TOKEN
        file: ./dist/cloudflare-ddns-linux-amd64.bin
        cleanup: true
        draft: true
        on:
          branch: master
          tags: true
