env:
  - BUILD_ID=${TRAVIS_BUILD_NUMBER}-${TRAVIS_COMMIT:0:7}

jobs:
  include:
    - stage: "Linux-amd64"
      name: "Build using Pyinstaller"
      os: linux
      language: python
      python: "3.9"
      script: 
        - bash .travis/test_python3.bash
        - bash .travis/build_binary.bash
    - name: "Linux-amd64"
      os: linux
      language: shell
      script: 
        - bash .travis/test_binary.bash

    - stage: "Linux-arm64"
      name: "Build using Pyinstaller"
#      if: branch = master OR branch = upgrade-aws-cli-v2 OR tag IS present
      if: branch = master OR tag IS present
      arch: arm64
      os: linux
      language: python
      python: "3.9"
      script: 
        - bash .travis/test_python3.bash
        - bash .travis/build_binary.bash
    - name: "Binary Test"
#      if: branch = master OR branch = upgrade-aws-cli-v2 OR tag IS present
      if: branch = master OR tag IS present
      arch: arm64
      os: linux
      language: shell
      script: 
        - bash .travis/test_binary.bash

    - stage: "OSX"
      name: "Build using Pyinstaller"
#      if: branch = master OR branch = upgrade-aws-cli-v2 OR tag IS present
      if: branch = master OR tag IS present
      os: osx
      osx_image: xcode11.2
      language: shell
      before_install:
        - python3 -m pip install --upgrade pip
      install:
        - python3 -m pip install -r requirements.txt
      script: 
        - bash .travis/test_python3.bash
        - bash .travis/build_binary.bash
    - name: "Mac OS X"
#      if: branch = master OR branch = upgrade-aws-cli-v2 OR tag IS present
      if: branch = master OR tag IS present
      os: osx
      language: shell
      script: 
        - bash .travis/test_binary.bash

    - stage: "Test and Build (Windows)"
      name: "Build using Pyinstaller (Windows)"
      if: branch = master OR branch = upgrade-aws-cli-v2 OR tag IS present
#      if: branch = master OR tag IS present
      os: windows
      language: shell
      env: 
        - BUILD_ID=${TRAVIS_BUILD_NUMBER}-${TRAVIS_COMMIT:0:7}
        - PATH=/c/Python39:/c/Python39/Scripts:$PATH
      before_install: 
        - echo $BUILD_ID
        - choco install python --version 3.9.0
      install:
        - pip3 install --user -r requirements.txt
      script: 
        - bash .travis/test_python3.bash
        - bash .travis/build_binary.bash
    - name: "Windows"
      if: branch = master OR branch = upgrade-aws-cli-v2 OR tag IS present
#      if: branch = master OR tag IS present
      os: windows
      language: shell
      script: 
       - bash .travis/test_binary.bash


    - stage: "Create Release Draft"
      os: linux
      language: python
      python: "3.6"
      if: branch = master AND type = push
      install:
        - pip install awscli
      script:
        - mkdir build
        - aws s3 cp s3://${AWS_TRAVIS_DEPLOY_BUCKET}/cloudflare_ddns/${BUILD_ID}/ ./build/ --recursive
        - ls -lR ./build
        - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
        - echo ${TRAVIS_TAG}
        - git tag $TRAVIS_TAG
      deploy:
        provider: releases
        token: $GITHUB_API_TOKEN
        file_glob: true
        file: ./build/*
        cleanup: false
        draft: true
        edge: true
        on:
          branch: master
          tags: true
      after_deploy:
        - aws s3 rm s3://${AWS_TRAVIS_DEPLOY_BUCKET}/cloudflare_ddns/ --recursive
