language: python
python:
  - "3.6"

env:
  - BUILD_ID=${TRAVIS_COMMIT:0:7}-${TRAVIS_BUILD_NUMBER}

jobs:
  include:
    - stage: "Python Tests"
      if: branch != build-matrix
      name: "Global API KEY test"
      env: 
        - EMAIL=cloudflare.kz21@torque.mikesoh.com
        - API_KEY=$GLOBAL_API_KEY
      before_script:
        - bash .travis/create_template.bash
      script:
        - python cloudflare-ddns.py -f -c .travis/cf_ddns.conf
    - name: "API Token test"
      if: branch != build-matrix
      env: 
        - API_KEY=$API_TOKEN
      before_script:
        - bash .travis/create_template.bash
      script:
        - python cloudflare-ddns.py -f -c .travis/cf_ddns.conf
    - stage: "Build Binaries"
      name: "Build using Pyinstaller (Linux-amd64)"
      arch:
        - amd64
      os: linux
      script: bash .travis/build_binary.bash
    - name: "Build using Pyinstaller (Linux-arm64)"
      arch:
        - arm64
      os: linux
      script: bash .travis/build_binary.bash
    - name: "Build using Pyinstaller (Mac OS)"
      os: osx
      script: bash .travis/build_binary.bash
    - name: "Build using Pyinstaller (Windows)"
      os: windows
      script: bash .travis/build_binary.bash
    - stage: "Create Release Draft"
      os: linux
      if: branch = master
      deploy:
        provider: releases
        token: $GITHUB_API_TOKEN
        file: ./dist/cloudflare-ddns-linux-amd64.bin
        cleanup: true
        draft: true
        on:
          branch: master
          tags: true
