language: python
python:
  - "3.6"

jobs:
  include:
    - stage: "Python Tests"
      if: branch = build-matrix
      name: "Global API KEY test"
      env: 
        - EMAIL=cloudflare.kz21@torque.mikesoh.com
        - API_KEY=$GLOBAL_API_KEY
      before_script:
        - bash .travis/create_template.bash
      script:
        - python cloudflare-ddns.py -f -c .travis/cf_ddns.conf
    - name: "API Token test"
      if: branch = build-matrix
      env: 
        - API_KEY=$API_TOKEN
      before_script:
        - bash .travis/create_template.bash
      script:
        - python cloudflare-ddns.py -f -c .travis/cf_ddns.conf
    - stage: "Build binaries"
      name: "Build using Pyinstaller (Linux)"
      os: linux
      script:
        - pip install awscli
        - pip install pyinstaller
        - pyinstaller --onefile ./cloudflare-ddns.py
        - export BIN_NAME=cloudflare-ddns-${TRAVIS_OS_NAME}-${TRAVIS_CPU_ARCH}.bin
        - cp ./dist/cloudflare-ddns ./dist/${BIN_NAME}
        - aws s3 cp ./dist/${BIN_NAME} s3://mikesoh.com-travis-ci.deployments/cloudflare_ddns/${TRAVIS_COMMIT:0:7}-${TRAVIS_BUILD_NUMBER}/
        - ls -lR
    - stage: "Create Release Draft"
      os: linux
      if: branch = master
      deploy:
        provider: releases
        token: $GITHUB_API_TOKEN
        file: ./dist/cloudflare-ddns-linux-amd64.bin
        cleanup: true
        cleanup: true
        draft: true
        on:
          branch: master
          tags: true
