language: python
python:
  - "3.6"

jobs:
  include:
    - stage: "Tests"
      name: "Global API KEY test"
      env: 
        - EMAIL=cloudflare.kz21@torque.mikesoh.com
        - API_KEY=$GLOBAL_API_KEY
      before_script:
        - bash .travis/create_template.bash
      script:
        - python cloudflare-ddns.py -f -c .travis/cf_ddns.conf
    - name: "API Token test"
      env: 
        - API_KEY=$API_TOKEN
      before_script:
        - bash .travis/create_template.bash
      script:
        - python cloudflare-ddns.py -f -c .travis/cf_ddns.conf
    - stage: "Build binaries"
      name: "Build using Pyinstaller (Linux)"
      os: linux
      script:
        - pip install pyinstaller
        - pyinstaller --onefile ./cloudflare-ddns.py
        - cp ./dist/cloudflare-ddns ./dist/cloudflare-ddns-linux-amd64.bin
        - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
        - git tag $TRAVIS_TAG
        - ls -lR
      deploy:
        provider: releases
        api_key: $GITHUB_API_TOKEN
        file: ./dist/cloudflare-ddns-linux-amd64.bin
        skip_cleanup: true
        draft: true
        on:
          branch: master
          tags: true
