env:
  - BUILD_ID=${TRAVIS_BUILD_NUMBER}-${TRAVIS_COMMIT:0:7}

jobs:
  include:
    - stage: Build and test arm binary
      name: "Build using Pyinstaller (Linux-arm64)"
      if: branch = main OR tag IS present
      arch: arm64
      os: linux
      language: python
      python: "3.9"
      script: 
        - bash ci/build_binary.bash
        - bash ci/test_binary.bash
        - bash ci/install_aws_cli
        - bash ci/upload_binary.bash        
    
    - stage: Deployment
      name: "Set git tag"
      os: linux
      arch: arm64
      language: shell
      script:
        - git tag ${GIT_TAG}
        - git push origin ${GIT_TAG}
        