name: Cloudflare DDNS

on: 
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - moving-to-github-actions
      - master
      - main
  release:
    types: published
  # schedule:
    # 4am every Saturday
    # - cron: '0 4 * * 6'

jobs:
  raw-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi      

      - name: Test Python Script
        run: bash .travis/test_python3.bash
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          GLOBAL_API_KEY: ${{ secrets.GLOBAL_API_KEY }}
          CF_EMAIL: ${{ secrets.CF_EMAIL }}
          TRAVIS_OS_NAME: linux
          SUBDOMAIN: travis
          ZONE: ${{ secrets.ZONE }}
  
  build-binaries:
    needs: raw-testing
    runs-on: [${{ matrix.os }}, ${{ matrix.arch }}]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        arch: [x64, ARM, ARM64]
        python-version: [3.9]

    steps:
      - name: Building LINUX Binaries
        run: bash .travis/build_binary.bash
        if: ${{ matrix.os == 'ubuntu-latest' }}
        env:
          TRAVIS_OS_NAME: linux
          TRAVIS_CPU_ARCH: ${{ matrix.arch }}
      
      - name: Building WINDOWS Binaries
        run: bash .travis/build_binary.bash
        if: ${{ matrix.os == 'windows-latest' }}
        env:
          TRAVIS_OS_NAME: windows
          TRAVIS_CPU_ARCH: ${{ matrix.arch }}
      